### ISSUE TITLE
Unable to install open cv

### ISSUE THREAD

**Issue by spartyboy** [php-opencv/php-opencv-examples#10]
Being trying to install open cv so as to use it in my laravel app but its not being working ever since? any ideas

**Comment by morozovsk** [comment]
nope

**Comment by spartyboy** [comment]
being unable to install libjasper for ubuntu 19.04 so as to build opencv

**Comment by morozovsk** [comment]
try [install from apk](https://github.com/php-opencv/php-opencv/wiki/Installation) instead of building
