### ISSUE TITLE
Is there any way to add new trains data?

### ISSUE THREAD

**Issue by Chuntianhong** [php-opencv/php-opencv-examples#12]
How are you?
Thank you for your sharing of great data.
I love it and I want to know the way to add new trains data dynamically.
Is there any way to implement it?
Thank you for your advice.

**Comment by morozovsk** [comment]
php-opencv is just wrapper for opencv, but opencv doesn't support training:
> [Functionality of this module is designed only for forward pass computations (i.e. network testing). A network training is in principle not supported.](https://docs.opencv.org/4.1.0/d6/d0f/group__dnn.html#details)

See also:
https://github.com/dstogov/php-tensorflow
https://github.com/tensorflow/tfjs-node

But I didn't use it.

**Comment by Arslan220** [comment]
i have a error plzz resolve it
Fatal error: Uncaught Error: Class 'CV\CascadeClassifier' not found in C:\xampp\htdocs\php-opencv-examples-master\recognize_face_by_lbph.php:9 Stack trace: #0 {main} thrown in C:\xampp\htdocs\php-opencv-examples-master\recognize_face_by_lbph.php on line 9
