### ISSUE TITLE
Installation via docker

### ISSUE THREAD

**Issue by ChanKimSiong** [php-opencv/php-opencv-examples#13]
https://github.com/php-opencv/php-opencv-examples/wiki/installation-via-docker
Use docker to install cannot install to local, only can test inside docker. Have another method to install opencv in windows?

**Comment by morozovsk** [comment]
I don't use windows so I don't know.

**Comment by ChanKimSiong** [comment]
Hi sir, https://github.com/php-opencv/php-opencv-examples/wiki/installation-via-docker
Have you use this method to install the project?

**Comment by morozovsk** [comment]
Yes, I used it for installation on ubuntu.

**Comment by ChanKimSiong** [comment]
Sir, can you zip your php-opencv-examples and open-cv folder then send it to me? Thank you.

**Comment by morozovsk** [comment]
no
