### ISSUE TITLE
How does the recognition work?

### ISSUE THREAD

**Issue by kimia000** [php-opencv/php-opencv-examples#14]
I get

```
php recognize_face_by_lbph.php
2, 88.481707039283
1, 113.10051890969
```

Isn't supposed to be the percentage?

When I replace the test page in recognize_face_by_lbph.php (images/angelina_and_me.png) with "images/2.jpg", where a match of 99% is expected, I get

```
php recognize_face_by_lbph.php // images2.jpg
1, 22.593326611433
```
```
php recognize_face_by_lbph.php // images1.jpg
1, 17.419620857298
```

**Comment by morozovsk** [comment]
I use a wrapper for LBPHFaceRecognizer.
You can find more information about LBPHFaceRecognizer on opencv site or google.
