### ISSUE TITLE
Call to undefined function CV\imread()

### ISSUE THREAD

**Issue by quangduz** [php-opencv/php-opencv-examples#15]
`
Fatal error: Uncaught Error: Call to undefined function CV\imread() in /var/www/html/php-opencv-examples/detect_face_by_dnn_ssd.php:10 Stack trace: #0 {main} thrown in /var/www/html/php-opencv-examples/detect_face_by_dnn_ssd.php on line 10
`

Worked in terminal command: php detect_face_by_dnn_ssd.php
`array (
  0 => 1,
  1 => 1,
  2 => 69,
  3 => 7,
)0.999955415725708
0.999824583530426`

But got error when run on localhost.

Please help !

**Comment by morozovsk** [comment]
You need to enable opencv module.
For example, you can enable it for console by the command:
echo "extension=opencv.so" > /etc/php/**7.2**/**cli**/conf.d/opencv.ini

You need to change it for your os, version of php and your web server.
