### ISSUE TITLE
Uncaught Error: Call to undefined function CV\imread()

### ISSUE THREAD

**Issue by dmytro-talko** [php-opencv/php-opencv-examples#16]
hi, i have this problem. i am installed opencv with this command:
`apt update && apt install -y wget && \
wget https://raw.githubusercontent.com/php-opencv/php-opencv-packages/master/opencv_4.0.1_amd64.deb && dpkg -i opencv_4.0.1_amd64.deb && rm opencv_4.0.1_amd64.deb && \
wget https://raw.githubusercontent.com/php-opencv/php-opencv-packages/master/php-opencv_7.2-4.0.1_amd64.deb && dpkg -i php-opencv_7.2-4.0.1_amd64.deb && rm php-opencv_7.2-4.0.1_amd64.deb && \
echo "extension=opencv.so" > /etc/php/7.2/cli/conf.d/opencv.ini`
Linux Mint 18.3 Sylvia
php 7.2.21

`PHP Warning:  PHP Startup: Unable to load dynamic library 'opencv.so' (tried: /usr/lib/php/20170718/opencv.so (/usr/lib/php/20170718/opencv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/opencv.so.so (/usr/lib/php/20170718/opencv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Fatal error:  Uncaught Error: Call to undefined function CV\imread() in /var/www/opencv.local/detect_face_by_dnn_ssd.php:7`

**Comment by morozovsk** [comment]
Check for existing in your file system files:
/usr/lib/php/20170718/opencv.so
/usr/local/lib/libopencv_dnn.so.4.0
/usr/local/lib/libopencv_dnn.so.4.0.1

If its don't exist then installation was with errors.
If its exist then your user doesn't have access for files.

How did you start php script? From console or web (apache/php-fmp/nginx unit)?

**Comment by osmankorucu** [comment]
Hi, i have same problem. @morozovsk i chceked thats files but i have not /usr/local/lib/libopencv_dnn.so.4.0 and /usr/local/lib/libopencv_dnn.so.4.0.1 files.

**Comment by morozovsk** [comment]
https://github.com/php-opencv/php-opencv-examples/issues/15
