### ISSUE TITLE
Call to undefined function CV\imread()

### ISSUE THREAD

**Issue by ykyazilim** [php-opencv/php-opencv-examples#21]
I am getting this error please can you help?
Is there any file I should include?

`[08-Dec-2020 20:33:05 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined function CV\imread() in /home/yusufkar/opencv.yusufkarakaya.com.tr/detect_objects_by_dnn_mobilenet.php:11
Stack trace:
#0 {main}
  thrown in /home/yusufkar/opencv.yusufkarakaya.com.tr/detect_objects_by_dnn_mobilenet.php on line 11
`

**Comment by morozovsk** [comment]
https://github.com/php-opencv/php-opencv-examples/issues/15
https://github.com/php-opencv/php-opencv-examples/issues/16
