### ISSUE TITLE
How to run your great works

### ISSUE THREAD

**Issue by AristoK3** [php-opencv/php-opencv-examples#23]
Hi, Vladmir. Thanks for posting such a great thing.
But unfortunately, I am a new baby in OpenCV, so I can't find a way to implement your work.
It would be so appreciated if you kindly guide me how to install OpenCV and integrate with PHP and run your code!!!
Please help me. I really wish to run these works.
Will wait for your kind explanation.

**Comment by morozovsk** [comment]
#### Installation (3 steps)
- [install opencv 4.0.0+](https://github.com/php-opencv/php-opencv/wiki/Installation.-opencv)
- [install php-opencv for your php version](https://github.com/php-opencv/php-opencv/wiki/Installation.-php-opencv)
- [install php-opencv-examples](https://github.com/php-opencv/php-opencv/wiki/Installation.-php-opencv-examples)
- [resolve problems](https://github.com/php-opencv/php-opencv/wiki/Installation.-troubleshooting) (if you need it)
