### ISSUE TITLE
Support for php7.3

### ISSUE THREAD

**Issue by killgt** [php-opencv/php-opencv-examples#5]
I'm triying to build the module and use it on php7.3, but it dump the core every time i try to run it, it's related to 7.3?

**Comment by morozovsk** [comment]
php 7.3 has broken internal api for extensions.
So php-opencv will not work on php 7.3+.
In future I will use [php-ffi](https://github.com/dstogov/php-ffi).
It was merged in [7.4](https://wiki.php.net/rfc/ffi) but will be realised only at the end of this year.

**Comment by Toutlemond** [comment]
Good day Vladimir ! Tell me what's wrong with my code. Example- Recognition_face_by_lbph.php is at the root of the site - it works great. But if I want to do the same in the my model, I get the error ERR_EMPTY_RESPONSE.
```

<?php
use CV\Face\LBPHFaceRecognizer, CV\CascadeClassifier, CV\Scalar, CV\Point;
use function CV\{imread, cvtColor, equalizeHist};
use const CV\{COLOR_BGR2GRAY};

class opencv_model extends Model
{
    function __construct()
    {
    }
    function recognize_face()
    {

        $faceClassifier = new CascadeClassifier();
        $faceClassifier->load(URL . 'phpocv/models/lbpcascades/lbpcascade_frontalface.xml');

        $faceRecognizer = LBPHFaceRecognizer::create();

        $filenam = __DIR__.'/faces.jpg';
        $labels = ['unknown', 'vadim', 'alice'];

        $src = cv\imread($filenam);
        $gray = cvtColor($src, COLOR_BGR2GRAY);
      // until this - everyfing work fine
       $faceClassifier->detectMultiScale($gray, $faces); // if i uncomment this line - all broke down...

        var_dump($faces);
      
    }
}
```

**Comment by karlbuckland** [comment]
Is there an update on when PHP 7.3 support might become available? Is anyone working on this already?

**Comment by morozovsk** [comment]
> Is anyone working on this already?
I think nobody.

**Comment by morozovsk** [comment]
apt update && apt install -y pkg-config cmake git php-dev
git clone https://github.com/php-opencv/php-opencv.git
cd php-opencv && git checkout php7.3 && phpize && ./configure --with-php-config=/usr/bin/php-config && make && make install
