### ISSUE TITLE
Example works great. But in the model - ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by Toutlemond** [php-opencv/php-opencv-examples#6]
Good day Vladimir ! 

Tell me what's wrong with my code. 
Example- Recognition_face_by_lbph.php is at the root of the site - it works great. 
But if I want to do the same in the my model, I get the error ERR_EMPTY_RESPONSE.
```


<?php
use CV\Face\LBPHFaceRecognizer, CV\CascadeClassifier, CV\Scalar, CV\Point;
use function CV\{imread, cvtColor, equalizeHist};
use const CV\{COLOR_BGR2GRAY};

class opencv_model extends Model
{
    function __construct()
    {
    }
    function recognize_face()
    {

        $faceClassifier = new CascadeClassifier();
        $faceClassifier->load(URL . 'phpocv/models/lbpcascades/lbpcascade_frontalface.xml');

        $faceRecognizer = LBPHFaceRecognizer::create();

        $filenam = __DIR__.'/faces.jpg';
        $labels = ['unknown', 'vadim', 'alice'];

        $src = cv\imread($filenam);
        $gray = cvtColor($src, COLOR_BGR2GRAY);
      // until this - everyfing work fine
       $faceClassifier->detectMultiScale($gray, $faces); // if i uncomment this line - all broke down...

        var_dump($faces);
      
    }
}
```

**Comment by morozovsk** [comment]
> Tell me what's wrong with my code.

A lot of problems :)

> filenam

typo

> $labels

didn't use

> $faceClassifier

didn't use

> //until this - everyfing work fine

did you check it? did you save $gray in file? Does it contain face?

**Comment by Toutlemond** [comment]
Hi!
Sorry 
The problem was here -

   ` $faceClassifier->load(URL . 'phpocv/models/lbpcascades/lbpcascade_frontalface.xml');`

The file was not read but did not throw out any error about it.

And everything broke.
I change it like this - 

`$lbpcascade = $_SERVER['DOCUMENT_ROOT'] . "/phpocv/models/lbpcascades/lbpcascade_frontalface.xml";
`

Thank you, for help and for library!
