### ISSUE TITLE
Can the next version support GaussianBlur  ?

### ISSUE THREAD

**Issue by lmafwo** [php-opencv/php-opencv-examples#8]
![image](https://user-images.githubusercontent.com/8241672/56813600-e1c5b580-686f-11e9-940b-3605e5689bee.png)

![image](https://user-images.githubusercontent.com/8241672/56813628-f1dd9500-686f-11e9-8543-d5ba7f23ed21.png)

**Comment by morozovsk** [comment]
https://github.com/hihozhou/php-opencv-ide-helper/search?q=GaussianBlur&unscoped_q=GaussianBlur
