### ISSUE TITLE
How to run the docker image

### ISSUE THREAD

**Issue by spartyboy** [php-opencv/php-opencv-examples#9]
how do i run the docker image of this package docker pull hihozhou/opencv and cofigure it]

**Comment by morozovsk** [comment]
https://github.com/php-opencv/php-opencv-examples/wiki/installation-via-docker

**Comment by spartyboy** [comment]
after running the docker image don't i need to modify my php.ini settings? if yes how?

**Comment by spartyboy** [comment]
how do i know opencv is working after launching the docker image? thanks

**Comment by morozovsk** [comment]
>how do i know opencv is working after launching the docker image?

`php detect_face_by_dnn_ssd.php`
